#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yuki Akutsu
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += int(line)
    except:   
       ans += float(line)

print(ans)

