#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yuki Akutsu
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
default_temp = 15.0

for line in sys.stdin:
    try:
        parts = line.split()
        if not parts:
            continue

        seconds = float(parts[0])

        if len(parts) > 1:
            temp = float(parts[1])
        else:
            temp = default_temp

        ans = (331.5 + 0.6 * temp) * seconds

    except ValueError:

        ans = 0
            
print(ans)
